# https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    ".",
    "tracking/common",
]

[package]
version = "0.0.0"
name = "rust-reviews"
publish = false
authors = ["MaulingMonkey <git@maulingmonkey.com>"]
edition = "2018"

[features]
default = []
